field.field.*.*.*.third_party.field_tag:
  type: mapping
  label: Field tag settings
  mapping:
    enabled:
      type: boolean
      label: 'Enable field tag'
    title:
      type: string
      label: 'Title'
    weight:
      type: integer
      label: 'Weight'
    description:
      type: text
      label: 'Description'
    placeholder:
      type: text
      label: 'Placeholder'
    required:
      type: boolean
      label: 'Required'
